export const GameEvents = {
  ChatHistory: 'chat:history',
  ChatSendMessage: 'chat:sendMessage',
  RoomCreate: 'room:create',
  RoomConfigureSetup: 'room:configureSetup',
  RoomList: 'room:list',
  RoomJoin: 'room:join',
  RoomLeave: 'room:leave',
  RoomState: 'room:state',
  RoomStart: 'room:start',
  RoomReady: 'room:ready',
  MatchMove: 'match:move',
  MatchSpectateJoin: 'match:spectateJoin',
  MatchSpectateLeave: 'match:spectateLeave',
  MatchForfeit: 'match:forfeit',
  MatchReconnect: 'match:reconnect',
  MatchRematchVote: 'match:rematchVote',
  SpectatorChatHistory: 'spectator:chatHistory',
  SpectatorChatSendMessage: 'spectator:sendMessage',
  ServerChatHistory: 'server:chatHistory',
  ServerChatMessage: 'server:chatMessage',
  ServerSpectatorChatHistory: 'server:spectatorChatHistory',
  ServerSpectatorChatMessage: 'server:spectatorChatMessage',
  ServerRoomUpdated: 'server:roomUpdated',
  ServerMatchUpdated: 'server:matchUpdated',
  ServerError: 'server:error',
} as const;

export type GameEventName = (typeof GameEvents)[keyof typeof GameEvents];
